version: "3.7"

services:
  db:
    image: "postgres:alpine"
    env_file: "./packages/platform/prisma/.env"
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data

volumes:
  data:
